# Generated by Django 4.0.6 on 2022-07-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comment_comment_date_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
    ]
