# Generated by Django 4.0.6 on 2022-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=100, verbose_name='tags (tags should divide by comma)'),
        ),
    ]
